# Generated by Django 4.1.2 on 2022-11-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_author_book_book_book_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='test',
            field=models.TextField(default=None, max_length=150),
        ),
    ]
