# Generated by Django 4.1.2 on 2022-11-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='author',
        ),
    ]
