# Generated by Django 4.1.2 on 2022-11-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_book_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='books', to='store.book'),
        ),
    ]
